#!/usr/bin/env python

import sys
import os
import argparse

home_dir = "/home/"
source_dir = "authorized_keys.d"
temp = "authorized_keys.temp"

parser = argparse.ArgumentParser(description="Tool that generates authorized_keys from authorized_keys.d")
parser.add_argument('-q', '--silent', action='store_true', help='Be completely quiet about all issues')
parser.add_argument('-f', '--force', action='store_true', help='Forcefully update the file, removing any files that prevent it')
params = parser.parse_args()

# Check if there is any directory for us
if (not os.path.isdir(source_dir)):
    if (not params.silent):
        print("Warning: no " + source_dir + " found in current directory")
    sys.exit(0)

if (os.path.exists(temp)):
    if (parser.force):
        os.remove(temp)
    else:
        print("Error: the temp file " + temp + " already exists, please remove it first, or use --force option")
        sys.exit(1)

files = os.listdir(source_dir)

text = "# This file is autogenerated using authorized_keys.d, please do not modify it by hand, it will be likely overwritten\n"

for file in files:
    path = source_dir + "/" + file
    if (not os.path.isdir(path)):
        with open(path, 'r') as fp:
            keys = fp.read()
            text = text + keys + "\n"

fp = open("authorized_keys", "w")
fp.write(text)
fp.close()
